# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UvPDMuds1bJt2Eh5AVtsYc8uaiuCA39b
"""



"""**Assignment**

create a python *list*
"""

# a list with 3 integers
numbers=[1,2,5]
print(numbers)

"""Tuple"""

# Tuple having integers
my_tuple = (1, 2, 3)
print(my_tuple)

# tuple with mixed datatypes
my_tuple = (1, "Hello", 3.4)
print(my_tuple)

# nested tuple
my_tuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(my_tuple)

"""*Set*"""

# create a set of integer type
student_id = {112, 114, 116, 118, 115}
print('Student ID:', student_id)

# create a set of string type
vowel_letters = {'a', 'e', 'i', 'o', 'u'}
print('Vowel Letters:', vowel_letters)

# create a set of mixed data types
mixed_set = {'Hello', 101, -2, 'Bye'}
print('Set of mixed data types:', mixed_set)

"""Dictionary"""

# dictionary with keys and values of different data types
numbers = {1: "One", 2: "Two", 3: "Three"}
print(numbers)

"""**3**.simple calculater*"""

number_1 = int(input('Enter your first number: '))
number_2 = int(input('Enter your second number: '))

print('{} + {} = '.format(number_1, number_2))
print(number_1 + number_2)

"""**Read**

Write
"""

#files->This is written by mama
#Three modes
#Read mode
#Write mode
#Append mode

myfile=open("a.txt","r")
print(myfile.read())

myfile.close()

myfile=open("a.txt","w")
myfile.write("This is writen by Mama\n")

myfile=open("a.txt","r")
print(myfile.read())

myfile=open("a.txt","a")
myfile.write("This is writen by Aparna\n")

myfile=open("a.txt","r")
print(myfile.read())